### ISSUE TITLE
Indigo compatibility

### ISSUE THREAD

**Issue by gpldecha** [RobotnikAutomation/barrett_hand#4]
I am currently using ros indigo and I have downloaded this package. I can load it in rviz no problem. However went I tried to launch the controller it tries to connect to the real physical hand. 

I am looking to control for the moment being only in simulation (Rviz + Gazebo) under indogo.
Is there any step I have missed to  simply run the controller in simulation ?

Thanks

**Comment by RomanRobotnik** [comment]
Hi!

Currently there's no tested version for Indigo.

On the other hand, there's no configuration to work properly with Gazebo.

I'll check it and try to upload one.

Regards

---

Román Navarro García

## R&D Department

Robotnik Automation, SLL                  Tel: (+34) 963383835
C/Berni y Catala, 53 bajo                    http://www.robotnik.eu
http://www.robotnik.es/

## 46019 - VALENCIA - SPAIN              rnavarro@robotnik.es

Follow us:

[image: Facebook] https://www.facebook.com/Robotnik.Automation  [image:
Youtube] https://www.youtube.com/user/RobotnikRobots  [image: Linkedin]
http://www.linkedin.com/company/robotnik-automation-sll  [image: Twitter]
https://twitter.com/RobotnikRobots                [image: www.robotnik.es]

## http://www.robotnik.es/
-   Aviso legal http://www.robotnik.es/politica-de-privacidad/ / Privacy
  policy http://www.robotnik.eu/privacy-policy/    -

2015-02-06 13:10 GMT+01:00 gpldecha notifications@github.com:

**Comment by gpldecha** [comment]
That would be great. There seams to be already a lot of source. However I would like
to try and get it to be fully integrated with Gazebo + Rviz + real hand, using ros_control
and indigo.

**Comment by RomanRobotnik** [comment]
Package for Gazebo is already ready for Indigo version at https://github.com/RobotnikAutomation/barrett_hand_sim.git
